name: morphos_assignment
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  get_storage: 
  hive:
  hive_flutter: 
  connectivity:
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  hive_generator:
  build_runner:
  flutter_launcher_icons: 
  flutter_test: 
    sdk: flutter


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo1.png"

flutter: 
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/images/

